name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:  # ✅ Allows manual execution for terraform destroy

jobs:
  terraform:
    name: "Terraform Init, Plan & Apply/Destroy"
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        working-directory: automation/terraform  # ✅ Set working directory

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event.inputs.destroy != 'true'  # ✅ Skip if destroy is requested
        run: terraform plan -var-file=dev.tfvars -out=tfplan

      - name: Terraform Apply (Only on Main Branch)
        if: github.ref == 'refs/heads/main' && github.event.inputs.destroy != 'true'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy (Manual Trigger)
        if: github.event.inputs.destroy == 'true'
        run: terraform destroy -auto-approve -var-file=dev.tfvars
