name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      action:
        description: "Select action: apply or destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      confirm_apply:
        description: "Type 'yes' to confirm apply (only required if action=apply)"
        required: false
        default: ""
      confirm_destroy:
        description: "Type 'yes' to confirm destroy (only required if action=destroy)"
        required: false
        default: ""

jobs:
  terraform:
    name: Terraform Init, Plan & Apply/Destroy
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        working-directory: automation/terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Determine Action (Auto vs. Manual)
        id: determine_action
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "action=apply" >> $GITHUB_ENV
          else
            echo "action=${{ github.event.inputs.action }}" >> $GITHUB_ENV
          fi

      - name: Terraform Plan
        if: env.action == 'apply'
        run: terraform plan -var-file=dev.tfvars -out=tfplan

      - name: Confirm Apply
        if: env.action == 'apply' && github.event_name == 'workflow_dispatch' && github.event.inputs.confirm_apply != 'yes'
        run: |
          echo "Apply operation was not confirmed. Exiting..."
          exit 1

      - name: Terraform Apply
        if: env.action == 'apply' && (github.event_name == 'push' || github.event.inputs.confirm_apply == 'yes')
        run: terraform apply -auto-approve tfplan

      - name: Confirm Destroy
        if: env.action == 'destroy' && github.event.inputs.confirm_destroy != 'yes'
        run: |
          echo "Destroy operation was not confirmed. Exiting..."
          exit 1

      - name: Terraform Destroy
        if: env.action == 'destroy' && github.event.inputs.confirm_destroy == 'yes'
        run: terraform destroy -auto-approve -var-file=dev.tfvars

