name: Terraform CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select action: apply or destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      confirm_apply:
        description: "Type 'yes' to confirm apply (only required if action=apply)"
        required: false
        default: ""
      confirm_destroy:
        description: "Type 'yes' to confirm destroy (only required if action=destroy)"
        required: false
        default: ""

jobs:
  terraform:
    name: Terraform Init, Plan & Apply/Destroy
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        working-directory: automation/terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Terraform Variables from S3
        run: |
          aws s3 cp s3://test-state-terrass-projs/dev.tfvars dev.tfvars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Set Terraform Action
        id: set_action
        run: echo "ACTION=${{ github.event.inputs.action }}" >> $GITHUB_ENV

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: env.ACTION == 'apply'
        run: terraform plan -var-file=dev.tfvars -out=tfplan

      - name: Confirm Apply
        if: env.ACTION == 'apply'
        run: |
          if [[ "${{ github.event.inputs.confirm_apply }}" != "yes" ]]; then
            echo "Apply operation was not confirmed. Exiting..."
            exit 1
          fi

      - name: Terraform Apply
        if: env.ACTION == 'apply'
        run: terraform apply -auto-approve tfplan

      - name: Confirm Destroy
        if: env.ACTION == 'destroy'
        run: |
          if [[ "${{ github.event.inputs.confirm_destroy }}" != "yes" ]]; then
            echo "Destroy operation was not confirmed. Exiting..."
            exit 1
          fi

      - name: Terraform Destroy
        if: env.ACTION == 'destroy'
        run: terraform destroy -auto-approve -var-file=dev.tfvars
